### ISSUE TITLE
Syntax error su ultimo aggiornamento

### ISSUE THREAD

**Issue by bigge32** [mappite/mappite#2]
Ciao, sull'ultima versione appena postata ci sono due problemi di compilazione js legati penso alla versione browser.
Io sto utilizzando una Ubuntu 16....
060-Layers : function openProtomapPopUp(e)

`//		for (var [sourceName, results] of layer.queryTileFeaturesDebug(ll.lng,ll.lat,8) ) {
		var results = layer.queryTileFeaturesDebug(ll.lng,ll.lat,8);
		for (var i = 0; i < results.length; i++) {
			//var sourceName = results[i][0];
			var result_out = results[i][1];
//            for (var result of result_out ) {
            for (k=0;k < result_out.lenght;k++ ) {
				var result = result_out[k];
		        var props = result.feature.props;
				var kind = props["pmap:kind"].replace("_", " ").toUpperCase();
				var kind_detail = props["pmap:kind_detail"].split("|");
`

050-markes:function selectPointType(id) {

`//	routeIconsMap.forEach(	(iconUrl, suffix) => {
	routeIconsMap.forEach(	function(iconUrl, suffix) {
`

Ho patchato per la compilazione che ora è ok ma sarebbe meglio controllare.

**Comment by eliboni** [comment]
I guess you're  using an old version of npm / uglify-js , pls.  test with at least 3.17 to support some advanced javascript notations.

**Comment by eliboni** [comment]
assume issue is due to old npm
